# Generated by Django 6.0.7 on 2026-09-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0002_medicationhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="is_repeating",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="period",
            field=models.CharField(default="Morning", max_length=20),
        ),
        migrations.AddField(
            model_name="reminder",
            name="snoozed_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
