# Generated by Django 6.0.7 on 2026-08-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="reminder_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="reminder_time",
            field=models.TimeField(default="09:00"),
        ),
    ]
