# Generated by Django 6.0.7 on 2026-09-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0004_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="reminder_times",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
