# Generated by Django 6.0.7 on 2026-09-07 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0006_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines",
                to="medicines.condition",
            ),
        ),
    ]
