# Generated by Django 6.0.7 on 2026-09-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0007_medicine_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="medication_category",
            field=models.CharField(
                choices=[
                    ("antibiotic", "Antibiotic"),
                    ("vitamin", "Vitamin / Supplement"),
                    ("pain_relief", "Pain Relief"),
                    ("heart", "Heart Medication"),
                    ("blood_pressure", "Blood Pressure Medication"),
                    ("cholesterol", "Cholesterol Medication"),
                    ("diabetes", "Diabetes Medication"),
                    ("thyroid", "Thyroid Medication"),
                    ("digestive", "Antacid / Digestive"),
                    ("allergy", "Allergy Medication"),
                    ("respiratory", "Respiratory Medication"),
                    ("anti_inflammatory", "Anti-inflammatory"),
                    ("antifungal", "Antifungal"),
                    ("antiviral", "Antiviral"),
                    ("neurological", "Neurological Medication"),
                    ("mental_health", "Mental Health Medication"),
                    ("skin", "Skin Medication"),
                    ("eye", "Eye Medication"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
